### ISSUE TITLE
Issue initiating transaction

### ISSUE THREAD

**Issue by SamjiDiamond** [matscode/paystack-php-sdk#2]
Using the example found on the readme is throwing an exception error.

Kindly look into correcting it.

$response = $Paystack->trasaction->initialize([
            'email'  => 'customer.email@gmail.com',
            'amount' => 500000, // amount is in kobo
            'callback_url' => 'https://www.app.local/paystack/transaction/verify'
        ]);

**Comment by matscode** [comment]
Thank you @SamjiDiamond . this would be fixed propmtly...
